### PR TITLE
Add wildcard search support

### PR DESCRIPTION
**Pull request by luuksommers**

### CODE REVIEW

**Comment by qetza** [comment]
Hi,
Thanks for the PR. I’ll do a quick review and test and if everything is ok i’ll merge and publish a new version.

**Comment by luuksommers** [comment]
Any update on this? 👍

**Comment by MacKinley** [comment]
Yes please!

**Comment by berendhaan** [comment]
Could use this in our CI/CD setup :)

**Comment by joshuacampbell1** [comment]
Could use it as well!

**Comment by iVova** [comment]
When will these changes be released?

**Comment by ajbeaven** [comment]
This is a vital improvement to this extension. Thanks @luuksommers for making it happen!

**Comment by qetza** [comment]
Hi,
Sorry for the really really long delay. I'm going to review the PR in the next weeks and release a new version around the end of the month.

**Pull request merged**
